spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
  jackson:
    deserialization:
      wrap-exceptions: false
